#!/bin/sh -e

umask 377

case "$1" in
pre)
	[ -z "$(ls -A /usr/lib/sysusers.d)" ] && exit 0
	grep -hEo "^(u|g).*" /usr/lib/sysusers.d/*.conf | awk '{print $1" "$2" "$3}' > /tmp/sysusers_pre
	chmod 400							     	       /tmp/sysusers_pre
;;
post)
	[ -z "$(ls -A /usr/lib/sysusers.d)" ] && exit 0
	grep -hEo "^(u|g).*" /usr/lib/sysusers.d/*.conf | awk '{print $1" "$2}' > /tmp/sysusers_post
	chmod 400							     	  /tmp/sysusers_post
	while read -r usergroup; do
		small="${usergroup#* }"; small="${small% *}"
		same="${usergroup##* }"; same="${same% *}"
		[ "$same" == "-" ] && andgroup=yes || andgroup=no
		if [[ "$usergroup" == "u "* ]]; then
			if [ "$(grep -x "u $small" /tmp/sysusers_post)" ]; then continue; else
				userdel -r "$small" &>/dev/null
				if [ "$andgroup" == yes ] && [ "$(grep -o "^$small:" /etc/group)" ]; then
					groupdel "$small"; nodel+=("$small")
				else
					nodel+=("$small")
				fi
			fi
		else
			if [ "$(grep -x "g $small" /tmp/sysusers_post)" ]; then continue; else
				if [ "$(echo ${nodel[@]} | tr " " "\n" | grep -x "$small")" ]; then continue; fi
				groupdel "$small"
			fi
		fi
		[ -d /var/lib/"$small" ] && rm -rf /var/lib/"$small"
	done < <(cat /tmp/sysusers_pre | sort -r)
	rm /tmp/sysusers_{post,pre}
;;
esac
exit 0
