#!/bin/bash
fifo=/usr/local/root.fifo
[ -p "$fifo" ] || { mkfifo "$fifo"; chmod 666 "$fifo"; }
fifouser=/usr/local/user.fifo
[ -p "$fifouser" ] || { mkfifo "$fifouser"; chmod 666 "$fifouser"; }
while [ -p "$fifo" ]; do
	line="$(cat "$fifo")"
	first="${line%%###*}"
	second="${line#*###}"
	bash -c "cd $first; $second" &> "$fifouser"
done
