#!/bin/bash
fp='/var/run/rc'
config='/etc/rc/daemon.conf'
[ -f $config ] || { echo "$config file does not exists"; exit 2; }
while read -r istrust; do
	list+="@$istrust@"
done < "$config"
_user="$USER"
[[ "${list}" == *"@$_user@"* ]] || { echo "You are not in the list of the configuration file $config"; exit 2; }
fifo=$fp/root:"$_user".fifo
[ -p "$fifo" ] || { echo "root_daemon is not running"; exit 1; }
fifouser=$fp/user:"$_user".fifo
_pwd="$(pwd)"
echo "$_pwd###$@" > "$fifo"
cat "$fifouser"
#echo "$(< "$fifouser")" # would be faster...
